In [4]:
import pickle

def read_pickle_file(file_path):
    with open(file_path, 'rb') as f:
        data = pickle.load(f)
    return data

# 使用示例
file_path = 'H:/NERF/data/USPTO/test_1_data.pickle'
loaded_data = read_pickle_file(file_path)

# 处理读取的数据
print(loaded_data)


[{'element': array([ 9,  6,  6,  6,  6,  6,  6,  9,  9,  7,  8,  8,  7,  6, 16,  6,  6,
        6,  6,  7, 11,  1,  6,  8,  6,  6,  6]), 'src_bond': array([[ 1,  0,  0,  0,  0,  0],
       [ 0,  2,  6,  1,  1,  1],
       [ 1,  3,  9,  2,  2,  2],
       [ 2,  4,  3,  3,  3,  3],
       [ 3,  5,  8,  4,  4,  4],
       [ 4,  6,  7,  5,  5,  5],
       [ 1,  5,  6,  6,  6,  6],
       [ 5,  7,  7,  7,  7,  7],
       [ 4,  8,  8,  8,  8,  8],
       [ 2, 10, 10, 11,  9,  9],
       [ 9,  9, 10, 10, 10, 10],
       [ 9, 11, 11, 11, 11, 11],
       [13, 12, 12, 12, 12, 12],
       [12, 14, 17, 13, 13, 13],
       [13, 15, 14, 14, 14, 14],
       [14, 16, 15, 15, 15, 15],
       [15, 17, 16, 16, 16, 16],
       [13, 16, 18, 17, 17, 17],
       [17, 19, 19, 19, 18, 18],
       [18, 18, 18, 19, 19, 19],
       [20, 20, 20, 20, 20, 20],
       [21, 21, 21, 21, 21, 21],
       [23, 26, 22, 22, 22, 22],
       [22, 24, 23, 23, 23, 23],
       [23, 25, 24, 24, 24, 24],
       [24, 26, 25, 25, 25

In [32]:
from dataset import TransformerDataset
from torch.utils.data import DataLoader

full_dataset = TransformerDataset(False, loaded_data)
data_loader = DataLoader(full_dataset, batch_size=2,
                         collate_fn = TransformerDataset.collate_fn)
data_loader

H:\NERF\dataset.py:19: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  tmp = torch.tensor(feature_dict[key])


In [30]:
c = 0
for batch in data_loader:
    if c == 0:    print(batch)
    c+= 1

{'element': tensor([[ 9,  6,  6,  6,  6,  6,  6,  9,  9,  7,  8,  8,  7,  6, 16,  6,  6,  6,
          6,  7, 11,  1,  6,  8,  6,  6,  6]]), 'src_bond': tensor([[[ 1,  0,  0,  0,  0,  0],
         [ 0,  2,  6,  1,  1,  1],
         [ 1,  3,  9,  2,  2,  2],
         [ 2,  4,  3,  3,  3,  3],
         [ 3,  5,  8,  4,  4,  4],
         [ 4,  6,  7,  5,  5,  5],
         [ 1,  5,  6,  6,  6,  6],
         [ 5,  7,  7,  7,  7,  7],
         [ 4,  8,  8,  8,  8,  8],
         [ 2, 10, 10, 11,  9,  9],
         [ 9,  9, 10, 10, 10, 10],
         [ 9, 11, 11, 11, 11, 11],
         [13, 12, 12, 12, 12, 12],
         [12, 14, 17, 13, 13, 13],
         [13, 15, 14, 14, 14, 14],
         [14, 16, 15, 15, 15, 15],
         [15, 17, 16, 16, 16, 16],
         [13, 16, 18, 17, 17, 17],
         [17, 19, 19, 19, 18, 18],
         [18, 18, 18, 19, 19, 19],
         [20, 20, 20, 20, 20, 20],
         [21, 21, 21, 21, 21, 21],
         [23, 26, 22, 22, 22, 22],
         [22, 24, 23, 23, 23, 23],
       

In [27]:
from tqdm import tqdm
pbar = tqdm(data_loader)
for batch in iter(pbar):
    print(batch['element'].to('cpu'))

100%|██████████| 2/2 [00:00<00:00, 1001.03it/s]

tensor([[ 9,  6,  6,  6,  6,  6,  6,  9,  9,  7,  8,  8,  7,  6, 16,  6,  6,  6,
          6,  7, 11,  1,  6,  8,  6,  6,  6]])
tensor([[ 6,  6,  7,  7,  6,  6,  6,  6,  8,  6,  6,  6,  6,  6,  6,  6,  6,  9,
          9,  9,  6, 15,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  8,  6,
          6,  6,  6,  7,  6,  6,  6,  6,  6,  6,  8,  6,  8,  6,  6,  6,  6,  6,
          6,  6]])


In [11]:
loaded_data[0]['element']

array([ 9,  6,  6,  6,  6,  6,  6,  9,  9,  7,  8,  8,  7,  6, 16,  6,  6,
        6,  6,  7, 11,  1,  6,  8,  6,  6,  6])

In [31]:
# [CH3:18][CH2:19][O:20][C:21](=[O:22])[Cl:23].[CH3:1][O:2][c:3]1[cH:4][c:5]2[n:6][c:7]([NH2:8])[c:9]([O:10][CH3:11])[n:12][c:13]2[cH:14][c:15]1[O:16][CH3:17].[cH:24]1[cH:25][cH:26][n:27][cH:28][cH:29]
loaded_data[0]['src_charge']

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0])

In [18]:
import re
line = "[CH3:18][CH2:19][O:20][C:21](=[O:22])[Cl:23].[CH3:1][O:2][c:3]1[cH:4][c:5]2[n:6][c:7]([NH2:8])[c:9]([O:10][CH3:11])[n:12][c:13]2[cH:14][c:15]1[O:16][CH3:17].[cH:24]1[cH:25][cH:26][n:27][cH:28][cH:29]1>>CCOC(=O)Nc1nc2cc(OC)c(OC)cc2nc1OC 8;;21-23-1.0;21-8-1.0"
rxn = line.split()[0].split(">>")
src = rxn[0]
tgt = rxn[1]

print(src)
print(tgt)

[CH3:18][CH2:19][O:20][C:21](=[O:22])[Cl:23].[CH3:1][O:2][c:3]1[cH:4][c:5]2[n:6][c:7]([NH2:8])[c:9]([O:10][CH3:11])[n:12][c:13]2[cH:14][c:15]1[O:16][CH3:17].[cH:24]1[cH:25][cH:26][n:27][cH:28][cH:29]1
CCOC(=O)Nc1nc2cc(OC)c(OC)cc2nc1OC


In [19]:
pattern = re.compile(":(\d+)\]")
pattern.findall(tgt)

[]

In [21]:
from rdkit import Chem
src_mols = src.split('.')
src_mols = [Chem.MolFromSmiles(item) for item in src_mols]
src_mols

In [22]:
tgt_mols = [Chem.MolFromSmiles(item) for item in tgt.split(".")]
tgt_mols

In [24]:
ranges = []
for mol in src_mols:
    lower = 999
    upper = 0
    for atom in mol.GetAtoms():
        print(atom.GetAtomMapNum())
        lower = min(lower, atom.GetAtomMapNum()-1)
        upper = max(upper, atom.GetAtomMapNum())
        print(lower, upper)
        print('-'*10)
    ranges.append((lower, upper))

18
17 18
----------
19
17 19
----------
20
17 20
----------
21
17 21
----------
22
17 22
----------
23
17 23
----------
1
0 1
----------
2
0 2
----------
3
0 3
----------
4
0 4
----------
5
0 5
----------
6
0 6
----------
7
0 7
----------
8
0 8
----------
9
0 9
----------
10
0 10
----------
11
0 11
----------
12
0 12
----------
13
0 13
----------
14
0 14
----------
15
0 15
----------
16
0 16
----------
17
0 17
----------
24
23 24
----------
25
23 25
----------
26
23 26
----------
27
23 27
----------
28
23 28
----------
29
23 29
----------


In [26]:
ranges

[(17, 23), (0, 17), (23, 29)]

In [40]:
atom

In [43]:
# Atom: [CH3:18][CH2:19][O:20][C:21](=[O:22])[Cl:23]
atom = src_mols[0].GetAtoms()[4]
for j,b in enumerate(atom.GetBonds()):
    print(j, b.GetBeginAtomIdx(), b.GetEndAtomIdx())
    print(b.GetBeginAtomIdx() + b.GetEndAtomIdx() - atom.GetIdx())
    print(b.GetBondType())

0 3 4
3
DOUBLE


In [12]:
def remove_lines_after_n(filename, n):
    with open(filename, 'r') as file:
        lines = file.readlines()

    # 保留前n行
    new_lines = lines[:n]

    with open(filename, 'w') as file:
        file.writelines(new_lines)

# 调用函数来删除第二行之后的所有内容
file_path = 'data/USPTO/test_1.txt'  # 将文件路径替换为你的文件路径
remove_lines_after_n(file_path, 2)


In [13]:
import torch
from torch.utils.data import Dataset, DataLoader

class CustomDataset(Dataset):
    def __init__(self, data):
        self.data = data

    def __len__(self):
        return len(self.data)

    def __getitem__(self, idx):
        return self.data[idx]

# 假设有两个句子的数据
data = [
    [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
    [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30]
]

dataset = CustomDataset(data)
dataloader = DataLoader(dataset, batch_size=2, shuffle=True)

for batch in dataloader:
    padded_batch = torch.nn.utils.rnn.pad_sequence(batch, batch_first=True, padding_value=0)
    print("原始batch：", batch)
    print("填充后的batch：", padded_batch)
    print("\n")


RuntimeError: each element in list of batch should be of equal size